
	$(document).ready(function(){
		$("#cee1").click(function(){
		$("#cee1").css('background-color','white');
		$("#cee1").css('color','black');
		$("#cee").css('display','inline');

		$("#bioe1").css('background-color','black');
		$("#bioe1").css('color','white')
		$("#bioe").css('display','none');
		$("#ee1").css('background-color','black');
		$("#ee1").css('color','white')
		$("#ee").css('display','none');
		$("#cs1").css('background-color','black');
		$("#cs1").css('color','white')
		$("#cs").css('display','none');
		$("#ieor1").css('background-color','black');
		$("#ieor1").css('color','white')
		$("#ieor").css('display','none');
		$("#mse1").css('background-color','black');
		$("#mse1").css('color','white')
		$("#mse").css('display','none');
		$("#me1").css('background-color','black');
		$("#me1").css('color','white')
		$("#me").css('display','none');
		$("#ne1").css('background-color','black');
		$("#ne1").css('color','white')
		$("#ne").css('display','none');
	});
	});


	$(document).ready(function(){
		$("#bioe1").click(function(){
		$("#bioe1").css('background-color','white');
		$("#bioe1").css('color','black');
		$("#bioe").css('display','inline');

		$("#cee1").css('background-color','black');
		$("#cee1").css('color','white')
		$("#cee").css('display','none');
		$("#ee1").css('background-color','black');
		$("#ee1").css('color','white')
		$("#ee").css('display','none');
		$("#cs1").css('background-color','black');
		$("#cs1").css('color','white')
		$("#cs").css('display','none');
		$("#ieor1").css('background-color','black');
		$("#ieor1").css('color','white')
		$("#ieor").css('display','none');
		$("#mse1").css('background-color','black');
		$("#mse1").css('color','white')
		$("#mse").css('display','none');
		$("#me1").css('background-color','black');
		$("#me1").css('color','white')
		$("#me").css('display','none');
		$("#ne1").css('background-color','black');
		$("#ne1").css('color','white')
		$("#ne").css('display','none');
	});
	});
	
	$(document).ready(function(){
		$("#ee1").click(function(){
		$("#ee1").css('background-color','white');
		$("#ee1").css('color','black');
		$("#ee").css('display','inline');

		$("#bioe1").css('background-color','black');
		$("#bioe1").css('color','white')
		$("#bioe").css('display','none');
		$("#cee1").css('background-color','black');
		$("#cee1").css('color','white')
		$("#cee").css('display','none');
		$("#cs1").css('background-color','black');
		$("#cs1").css('color','white')
		$("#cs").css('display','none');
		$("#ieor1").css('background-color','black');
		$("#ieor1").css('color','white')
		$("#ieor").css('display','none');
		$("#mse1").css('background-color','black');
		$("#mse1").css('color','white')
		$("#mse").css('display','none');
		$("#me1").css('background-color','black');
		$("#me1").css('color','white')
		$("#me").css('display','none');
		$("#ne1").css('background-color','black');
		$("#ne1").css('color','white')
		$("#ne").css('display','none');
	});
	});
	
	$(document).ready(function(){
		$("#cs1").click(function(){
		$("#cs1").css('background-color','white');
		$("#cs1").css('color','black');
		$("#cs").css('display','inline');

		$("#bioe1").css('background-color','black');
		$("#bioe1").css('color','white')
		$("#bioe").css('display','none');
		$("#ee1").css('background-color','black');
		$("#ee1").css('color','white')
		$("#ee").css('display','none');
		$("#cee1").css('background-color','black');
		$("#cee1").css('color','white')
		$("#cee").css('display','none');
		$("#ieor1").css('background-color','black');
		$("#ieor1").css('color','white')
		$("#ieor").css('display','none');
		$("#mse1").css('background-color','black');
		$("#mse1").css('color','white')
		$("#mse").css('display','none');
		$("#me1").css('background-color','black');
		$("#me1").css('color','white')
		$("#me").css('display','none');
		$("#ne1").css('background-color','black');
		$("#ne1").css('color','white')
		$("#ne").css('display','none');
	});
	});
	
	$(document).ready(function(){
		$("#ieor1").click(function(){
		$("#ieor1").css('background-color','white');
		$("#ieor1").css('color','black');
		$("#ieor").css('display','inline');

		$("#bioe1").css('background-color','black');
		$("#bioe1").css('color','white')
		$("#bioe").css('display','none');
		$("#ee1").css('background-color','black');
		$("#ee1").css('color','white')
		$("#ee").css('display','none');
		$("#cs1").css('background-color','black');
		$("#cs1").css('color','white')
		$("#cs").css('display','none');
		$("#cee1").css('background-color','black');
		$("#cee1").css('color','white')
		$("#cee").css('display','none');
		$("#mse1").css('background-color','black');
		$("#mse1").css('color','white')
		$("#mse").css('display','none');
		$("#me1").css('background-color','black');
		$("#me1").css('color','white')
		$("#me").css('display','none');
		$("#ne1").css('background-color','black');
		$("#ne1").css('color','white')
		$("#ne").css('display','none');
	});
	});
	
	$(document).ready(function(){
		$("#mse1").click(function(){
		$("#mse1").css('background-color','white');
		$("#mse1").css('color','black');
		$("#mse").css('display','inline');

		$("#bioe1").css('background-color','black');
		$("#bioe1").css('color','white')
		$("#bioe").css('display','none');
		$("#ee1").css('background-color','black');
		$("#ee1").css('color','white')
		$("#ee").css('display','none');
		$("#cs1").css('background-color','black');
		$("#cs1").css('color','white')
		$("#cs").css('display','none');
		$("#ieor1").css('background-color','black');
		$("#ieor1").css('color','white')
		$("#ieor").css('display','none');
		$("#cee1").css('background-color','black');
		$("#cee1").css('color','white')
		$("#cee").css('display','none');
		$("#me1").css('background-color','black');
		$("#me1").css('color','white')
		$("#me").css('display','none');
		$("#ne1").css('background-color','black');
		$("#ne1").css('color','white')
		$("#ne").css('display','none');
	});
	});
	
	$(document).ready(function(){
		$("#me1").click(function(){
		$("#me1").css('background-color','white');
		$("#me1").css('color','black');
		$("#me").css('display','inline');

		$("#bioe1").css('background-color','black');
		$("#bioe1").css('color','white')
		$("#bioe").css('display','none');
		$("#ee1").css('background-color','black');
		$("#ee1").css('color','white')
		$("#ee").css('display','none');
		$("#cs1").css('background-color','black');
		$("#cs1").css('color','white')
		$("#cs").css('display','none');
		$("#ieor1").css('background-color','black');
		$("#ieor1").css('color','white')
		$("#ieor").css('display','none');
		$("#mse1").css('background-color','black');
		$("#mse1").css('color','white')
		$("#mse").css('display','none');
		$("#cee1").css('background-color','black');
		$("#cee1").css('color','white')
		$("#cee").css('display','none');
		$("#ne1").css('background-color','black');
		$("#ne1").css('color','white')
		$("#ne").css('display','none');
	});
	});
	
	$(document).ready(function(){
		$("#ne1").click(function(){
		$("#ne1").css('background-color','white');
		$("#ne1").css('color','black');
		$("#ne").css('display','inline');

		$("#bioe1").css('background-color','black');
		$("#bioe1").css('color','white')
		$("#bioe").css('display','none');
		$("#ee1").css('background-color','black');
		$("#ee1").css('color','white')
		$("#ee").css('display','none');
		$("#cs1").css('background-color','black');
		$("#cs1").css('color','white')
		$("#cs").css('display','none');
		$("#ieor1").css('background-color','black');
		$("#ieor1").css('color','white')
		$("#ieor").css('display','none');
		$("#mse1").css('background-color','black');
		$("#mse1").css('color','white')
		$("#mse").css('display','none');
		$("#me1").css('background-color','black');
		$("#me1").css('color','white')
		$("#me").css('display','none');
		$("#cee1").css('background-color','black');
		$("#cee1").css('color','white')
		$("#cee").css('display','none');
	});
	});
	